export const HEADER_NAV = [
  { label: "Возможности", href: "../home/index.html#discover", active: true },
  { label: "Работодатели / Компании", href: "../company/company-dashboard.html" },
  { label: "Соискатели", href: "../candidate/candidate-profile.html" },
];

export const SIDEBAR_ITEMS = [
  { key: "dashboard", label: "Дашборд", href: "./moderator-dashboard.html" },
  { key: "opportunities", label: "Модерация возможностей", href: "./moderator-opportunities.html" },
  { key: "companies", label: "Верификация компаний", href: "./moderator-companies.html" },
  { key: "users", label: "Пользователи", href: "./moderator-users.html" },
  { key: "reports", label: "Жалобы", href: "./moderator-reports.html" },
  { key: "tags", label: "Теги и система" },
  { key: "logs", label: "Логи", href: "./moderator-logs.html" },
  { key: "settings", label: "Настройки", href: "./moderator-settings.html" },
];

export const MODERATOR_SUMMARY = {
  eyebrow: "Смена куратора",
  count: "14 задач",
  text: "На очереди 4 возможности, 4 компании и 6 жалоб.",
};

export const DASHBOARD_METRICS = [
  {
    value: "4",
    title: "Возможности на проверке",
    note: "В очереди приоритетные вакансии и стажировки",
  },
  {
    value: "4",
    title: "Компании на верификации",
    note: "Проверяем сайт, домен и документы",
  },
  {
    value: "6",
    title: "Жалобы",
    note: "Жалобы сгруппированы по объектам",
  },
];

export const ACTIVITY_FILTERS = ["Все", "Жалобы", "Возможности", "Пользователи", "Компании"];

export const ACTIVITY_ITEMS = [
  {
    id: "activity-1",
    type: "Возможность",
    filter: "Возможности",
    title: "Создана вакансия Signal Hub",
    description: "Компания отправила на проверку стажировку в продуктовой аналитике.",
    date: "19 марта · 11:20",
  },
  {
    id: "activity-2",
    type: "Компания",
    filter: "Компании",
    title: "Профиль компании обновлён",
    description: "Cloud Orbit HR изменил описание команды и контактное лицо.",
    date: "19 марта · 11:20",
  },
  {
    id: "activity-3",
    type: "Пользователь",
    filter: "Пользователи",
    title: "Заблокирован пользователь",
    description: "Аккаунт Ильи Смирнова ограничен по повторным жалобам на спам.",
    date: "19 марта · 11:20",
  },
];

export const SHIFT_ITEMS = [
  {
    title: "Возможности на проверке",
    description: "В очереди приоритетные вакансии и стажировки",
    status: "4 в работе",
  },
  {
    title: "Компании на верификации",
    description: "Проверяем сайт, домен и документы",
    status: "4 в работе",
  },
  {
    title: "Жалобы",
    description: "Жалобы сгруппированы по объектам",
    status: "6 в работе",
  },
];

export const QUEUE_FILTERS = ["Все", "Жалобы", "Возможности", "Верификация"];

export const QUEUE_ITEMS = [
  {
    id: "queue-1",
    type: "Жалоба",
    filter: "Жалобы",
    title: "Junior Security Analyst",
    description: "Недостоверная зарплата: 6 жалоб",
    date: "19 марта 2026",
  },
  {
    id: "queue-2",
    type: "Вакансия",
    filter: "Возможности",
    title: "DevRel Assistant",
    description: "Трамплин Platform · Высокий приоритет",
    date: "19 марта 2026",
  },
  {
    id: "queue-3",
    type: "Верификация",
    filter: "Верификация",
    title: "Neuro Campus",
    description: "Требуется верификация компании",
    date: "19 марта 2026",
  },
];

export const MODERATION_FILTERS = ["Все", "На проверке", "Одобрено", "Доработка", "Отклонено"];

export const MODERATION_ITEMS = [
  {
    id: "opportunity-1",
    title: "Стажировка в продуктовой аналитике",
    company: "Signal Hub",
    type: "Стажировка",
    date: "19.03.2026",
    status: "На проверке",
    statusKey: "pending",
    format: "Гибрид",
    salary: "60 000 ₽ / мес",
    publishedAt: "19 марта 2026",
    description:
      "Стажировка для студентов 3–4 курса: продуктовые метрики, SQL, A/B-тесты и работа с наставником в growth-команде.",
    tags: ["SQL", "Growth", "BI"],
    media: ["Превью лендинга", "Программа стажировки"],
  },
  {
    id: "opportunity-2",
    title: "Junior Security Analyst",
    company: "Киберполигон",
    type: "Вакансия",
    date: "19.03.2026",
    status: "На проверке",
    statusKey: "pending",
    format: "Офис / гибрид",
    salary: "от 90 000 ₽",
    publishedAt: "18 марта 2026",
    description: "Стартовая роль в SOC-команде: мониторинг инцидентов, SIEM и работа с наставником на старте.",
    tags: ["SOC", "SIEM", "Junior"],
    media: ["Карточка вакансии", "Скрин требований"],
  },
  {
    id: "opportunity-3",
    title: "AI Product Sprint",
    company: "Трамплин Platform",
    type: "Мероприятие",
    date: "18.03.2026",
    status: "Доработка",
    statusKey: "revision",
    format: "Онлайн + Москва",
    salary: "Регистрация",
    publishedAt: "17 марта 2026",
    description: "Нужно уточнить дедлайн регистрации и состав спикеров перед повторной публикацией.",
    tags: ["AI", "Product", "Спринт"],
    media: ["Баннер события", "План программы"],
  },
  {
    id: "opportunity-4",
    title: "Frontend Trainee",
    company: "Cloud Orbit",
    type: "Вакансия",
    date: "18.03.2026",
    status: "Одобрено",
    statusKey: "approved",
    format: "Гибрид",
    salary: "от 70 000 ₽",
    publishedAt: "17 марта 2026",
    description: "Практика на стыке интерфейсов и design-system процесса. Карточка уже прошла модерацию.",
    tags: ["React", "UI", "Design System"],
    media: ["Карточка компании", "Стек команды"],
  },
  {
    id: "opportunity-5",
    title: "Design Bootcamp",
    company: "Product Lab",
    type: "Стажировка",
    date: "17.03.2026",
    status: "Отклонено",
    statusKey: "rejected",
    format: "Онлайн",
    salary: "35 000 ₽ / мес",
    publishedAt: "16 марта 2026",
    description: "Недостаточно прозрачные условия и отсутствует подтверждённое контактное лицо.",
    tags: ["UI", "Portfolio", "Review"],
    media: ["Постер", "Описание трека"],
  },
  {
    id: "opportunity-6",
    title: "Data Lab Intern",
    company: "Data Forge",
    type: "Стажировка",
    date: "16.03.2026",
    status: "На проверке",
    statusKey: "pending",
    format: "Офис",
    salary: "50 000 ₽ / мес",
    publishedAt: "16 марта 2026",
    description: "Стажировка в data-команде с фокусом на dashboards, SQL и первые продуктовые исследования.",
    tags: ["Data", "Python", "SQL"],
    media: ["План стажировки", "Превью дашборда"],
  },
  {
    id: "opportunity-7",
    title: "DevRel Assistant",
    company: "Трамплин Platform",
    type: "Вакансия",
    date: "16.03.2026",
    status: "На проверке",
    statusKey: "pending",
    format: "Онлайн",
    salary: "от 80 000 ₽",
    publishedAt: "15 марта 2026",
    description: "Роль для кандидата, который умеет собирать комьюнити и вести карьерные события платформы.",
    tags: ["Community", "Events", "Writing"],
    media: ["Описание роли", "Команда DevRel"],
  },
  {
    id: "opportunity-8",
    title: "MLOps Practice Track",
    company: "Orbit Labs",
    type: "Стажировка",
    date: "15.03.2026",
    status: "Доработка",
    statusKey: "revision",
    format: "Гибрид",
    salary: "65 000 ₽ / мес",
    publishedAt: "15 марта 2026",
    description: "Нужно уточнить длительность трека и формат участия в офисные дни.",
    tags: ["MLOps", "Docker", "Kubernetes"],
    media: ["Программа трека", "Схема пайплайна"],
  },
  {
    id: "opportunity-9",
    title: "Cyber Career Meetup",
    company: "Edge Security",
    type: "Мероприятие",
    date: "14.03.2026",
    status: "Одобрено",
    statusKey: "approved",
    format: "Москва",
    salary: "Регистрация",
    publishedAt: "14 марта 2026",
    description: "Оффлайн-встреча по карьерным трекам в кибербезопасности с быстрыми собеседованиями.",
    tags: ["Meetup", "Security", "Networking"],
    media: ["Постер", "Список спикеров"],
  },
];

export const COMPANY_FILTERS = ["Все", "На проверке", "Подтверждены", "Доработка", "Отклонено"];

export const COMPANY_ITEMS = [
  {
    id: "company-1",
    name: "Север Digital",
    email: "career@severdigital.ru",
    site: "severdigital.ru",
    date: "19.03.2026",
    status: "На проверке",
    statusKey: "pending",
    description:
      "Продуктовая IT-команда из Санкт-Петербурга. Публикует вакансии по аналитике и frontend, ищет студентов для стажировок.",
    socials: "Telegram, VK",
    documents: "ИНН.pdf, ОГРН.pdf",
    detailNote:
      "Стажировка для студентов 3–4 курса: продуктовые метрики, SQL, A/B-тесты и работа с наставником в growth-команде.",
    checks: [
      { label: "Есть сайт", state: "success" },
      { label: "Не совпадает домен", state: "warning" },
      { label: "Есть соцсети", state: "success" },
    ],
  },
  {
    id: "company-2",
    name: "Neuro Campus",
    email: "team@neurocampus.team",
    site: "neurocampus.team",
    date: "19.03.2026",
    status: "Доработка",
    statusKey: "revision",
    description:
      "Образовательный стартап с карьерными интенсивами. Запрошены дополнительные данные по юридическому лицу и домену сайта.",
    socials: "Telegram",
    documents: "Презентация.pdf",
    detailNote: "Команда просит время на обновление домена и публикацию дополнительных юридических данных.",
    checks: [
      { label: "Есть сайт", state: "success" },
      { label: "Нужны документы", state: "warning" },
      { label: "Есть соцсети", state: "success" },
    ],
  },
  {
    id: "company-3",
    name: "Data Forge",
    email: "jobs@dataforge.ru",
    site: "dataforge.ru",
    date: "18.03.2026",
    status: "Подтверждены",
    statusKey: "approved",
    description:
      "Команда аналитических платформ уже верифицирована и публикует вакансии в контуре работодателей.",
    socials: "VK, Сайт",
    documents: "ИНН.pdf, ОГРН.pdf, Реквизиты.pdf",
    detailNote: "Профиль заполнен, документы подтверждены, дополнительных действий не требуется.",
    checks: [
      { label: "Есть сайт", state: "success" },
      { label: "Совпадает домен", state: "success" },
      { label: "Есть соцсети", state: "success" },
    ],
  },
  {
    id: "company-4",
    name: "Orbit Labs",
    email: "careers@orbitlabs.ai",
    site: "orbitlabs.ai",
    date: "18.03.2026",
    status: "Отклонено",
    statusKey: "rejected",
    description:
      "Запрос отклонён после первичной проверки: часть корпоративных контактов не подтверждена и документы не совпадают.",
    socials: "Telegram, LinkedIn",
    documents: "ИНН.pdf",
    detailNote: "Нужно подать заявку повторно после обновления документов и доменной почты.",
    checks: [
      { label: "Есть сайт", state: "success" },
      { label: "Не совпадает домен", state: "warning" },
      { label: "Не хватает документов", state: "warning" },
    ],
  },
  {
    id: "company-5",
    name: "Mentor Space",
    email: "hello@mentor-space.ru",
    site: "mentor-space.ru",
    date: "17.03.2026",
    status: "На проверке",
    statusKey: "pending",
    description:
      "Карьерный сервис с менторскими программами и онлайн-мероприятиями. Подал заявку на публикацию компании и событий.",
    socials: "Telegram, VK",
    documents: "ИНН.pdf",
    detailNote: "Ожидаем подтверждение юридического лица и финальную проверку брендовых материалов.",
    checks: [
      { label: "Есть сайт", state: "success" },
      { label: "Совпадает домен", state: "success" },
      { label: "Есть соцсети", state: "success" },
    ],
  },
  {
    id: "company-6",
    name: "Code River",
    email: "hr@coderiver.dev",
    site: "coderiver.dev",
    date: "17.03.2026",
    status: "Подтверждены",
    statusKey: "approved",
    description:
      "Разработчики B2B-сервисов. Компания подтверждена и уже публикует вакансии для backend и frontend направления.",
    socials: "VK, Сайт",
    documents: "ИНН.pdf, ОГРН.pdf",
    detailNote: "Все поля валидны, заявка закрыта успешно.",
    checks: [
      { label: "Есть сайт", state: "success" },
      { label: "Совпадает домен", state: "success" },
      { label: "Есть соцсети", state: "success" },
    ],
  },
];

export const USER_FILTERS = ["Все", "Соискатели", "Работодатели", "Заблокированы", "Удалены"];

export const USER_ITEMS = [
  {
    id: "user-1",
    name: "Алина Петрова",
    role: "Соискатель",
    roleKey: "candidate",
    date: "19.03.2026",
    status: "Активен",
    statusKey: "active",
    contextLabel: "Команда / вуз",
    contextValue: "МГТУ им. Баумана",
    lastSeen: "10 минут назад",
    summary: "4 курс, аналитика продукта, отклики в Signal Hub и Трамплин Platform.",
  },
  {
    id: "user-2",
    name: "Илья Смирнов",
    role: "Соискатель",
    roleKey: "candidate",
    date: "19.03.2026",
    status: "Удалён",
    statusKey: "deleted",
    contextLabel: "Команда / вуз",
    contextValue: "НИУ ВШЭ",
    lastSeen: "сегодня в 09:15",
    summary: "Удалён после подтверждённых жалоб на массовые повторяющиеся сообщения.",
  },
  {
    id: "user-3",
    name: "Мария Лебедева",
    role: "Соискатель",
    roleKey: "candidate",
    date: "19.03.2026",
    status: "Заблокирован",
    statusKey: "blocked",
    contextLabel: "Команда / вуз",
    contextValue: "ИТМО",
    lastSeen: "сегодня в 08:40",
    summary: "Временная блокировка на 7 дней после повторной модерации откликов.",
  },
  {
    id: "user-4",
    name: "Алексей Орлов",
    role: "Работодатель",
    roleKey: "employer",
    date: "19.03.2026",
    status: "Активен",
    statusKey: "active",
    contextLabel: "Компания",
    contextValue: "Signal Hub",
    lastSeen: "25 минут назад",
    summary: "Публикует вакансии и стажировки, подтверждённый менеджер со стороны работодателя.",
  },
  {
    id: "user-5",
    name: "Полина Власова",
    role: "Соискатель",
    roleKey: "candidate",
    date: "19.03.2026",
    status: "Активен",
    statusKey: "active",
    contextLabel: "Команда / вуз",
    contextValue: "СПбГУ",
    lastSeen: "1 час назад",
    summary: "Активно откликается на роли в аналитике и участвует в карьерных мероприятиях.",
  },
  {
    id: "user-6",
    name: "Cloud Orbit HR",
    role: "Работодатель",
    roleKey: "employer",
    date: "18.03.2026",
    status: "Заблокирован",
    statusKey: "blocked",
    contextLabel: "Компания",
    contextValue: "Cloud Orbit",
    lastSeen: "вчера в 21:10",
    summary: "Ограничен до завершения проверки массовой рассылки приглашений кандидатам.",
  },
  {
    id: "user-7",
    name: "Кирилл Савин",
    role: "Соискатель",
    roleKey: "candidate",
    date: "18.03.2026",
    status: "Заблокирован",
    statusKey: "blocked",
    contextLabel: "Команда / вуз",
    contextValue: "Университет Иннополис",
    lastSeen: "вчера в 18:05",
    summary: "Заблокирован после серии жалоб на спам и нерелевантные отклики.",
  },
  {
    id: "user-8",
    name: "Mentor Space Team",
    role: "Работодатель",
    roleKey: "employer",
    date: "18.03.2026",
    status: "Удалён",
    statusKey: "deleted",
    contextLabel: "Компания",
    contextValue: "Mentor Space",
    lastSeen: "вчера в 12:35",
    summary: "Профиль скрыт до повторной верификации бренда и контактов компании.",
  },
];

export const REPORT_ITEMS = [
  {
    id: "report-1",
    title: "Junior Security Analyst",
    reason: "Недостоверная зарплата",
    date: "19 марта 2026",
    timestamp: 202603191120,
    count: 6,
    description: "Жалобы объединены по одной вакансии: пользователи указывают на некорректную зарплатную вилку в описании.",
  },
  {
    id: "report-2",
    title: "Signal Hub HR",
    reason: "Дублирующиеся сообщения кандидатам",
    date: "19 марта 2026",
    timestamp: 202603191015,
    count: 5,
    description: "Группа жалоб на массовые приглашения в отклики без персонализации. Требуется сверка шаблонов рассылки.",
  },
  {
    id: "report-3",
    title: "Signal Hub HR",
    reason: "Спам в откликах",
    date: "18 марта 2026",
    timestamp: 202603181740,
    count: 4,
    description: "Жалобы связаны с массовыми откликами без релевантного сопроводительного текста.",
  },
  {
    id: "report-4",
    title: "Orbit Labs",
    reason: "Подмена домена в контактах",
    date: "18 марта 2026",
    timestamp: 202603181505,
    count: 4,
    description: "Пользователи заметили несоответствие между корпоративным доменом компании и адресом для обратной связи.",
  },
  {
    id: "report-5",
    title: "Product Design Meetup",
    reason: "Старый дедлайн регистрации",
    date: "17 марта 2026",
    timestamp: 202603171630,
    count: 3,
    description: "Организатор не обновил дедлайн на карточке мероприятия, из-за чего участники получают устаревшую информацию.",
  },
  {
    id: "report-6",
    title: "Data Forge",
    reason: "Неверное описание графика",
    date: "17 марта 2026",
    timestamp: 202603171020,
    count: 3,
    description: "Кандидаты сообщают, что в объявлении указан гибрид, но в переписке компания требует полный офис.",
  },
  {
    id: "report-7",
    title: "Mentor Space",
    reason: "Скрыты контакты работодателя",
    date: "16 марта 2026",
    timestamp: 202603161540,
    count: 2,
    description: "Жалобы на отсутствие актуального контактного лица и невозможность связаться после отклика.",
  },
];

export const LOG_FILTERS = ["Все", "Возможности", "Компании", "Пользователи", "Модерация"];

export const LOG_ITEMS = [
  {
    id: "log-1",
    type: "Возможность",
    filter: "Возможности",
    title: "Создана вакансия Signal Hub",
    description: "Компания отправила на проверку стажировку в продуктовой аналитике.",
    date: "19 марта · 11:20",
  },
  {
    id: "log-2",
    type: "Компания",
    filter: "Компании",
    title: "Профиль компании обновлён",
    description: "Cloud Orbit HR изменил описание команды и контактное лицо.",
    date: "19 марта · 10:45",
  },
  {
    id: "log-3",
    type: "Пользователь",
    filter: "Пользователи",
    title: "Заблокирован пользователь",
    description: "Аккаунт Ильи Смирнова ограничен по повторным жалобам на спам.",
    date: "19 марта · 10:45",
  },
  {
    id: "log-4",
    type: "Модерация",
    filter: "Модерация",
    title: "Карточка отправлена на доработку",
    description: "MLOps Practice Track возвращён работодателю с комментарием по формату участия.",
    date: "18 марта · 17:40",
  },
  {
    id: "log-5",
    type: "Возможность",
    filter: "Возможности",
    title: "Отклонено событие Career Sprint",
    description: "Не подтверждены спикеры и отсутствует актуальная ссылка на регистрацию.",
    date: "18 марта · 15:20",
  },
];
