// <auto-generated />
using System;
using System.Collections.Generic;
using Application.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace ITPlanetaTramplin.Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260324075128_projectsCreated")]
    partial class projectsCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.ApplicantAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer")
                        .HasColumnName("applicant_id");

                    b.PrimitiveCollection<List<string>>("Attachments")
                        .HasColumnType("character varying(500)[]")
                        .HasColumnName("attachments");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<DateOnly?>("ObtainDate")
                        .HasColumnType("date")
                        .HasColumnName("obtain_date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("applicant_achievements_pkey");

                    b.HasIndex(new[] { "ApplicantId" }, "idx_applicant_achievements_applicant_id");

                    b.ToTable("applicant_achievements", (string)null);
                });

            modelBuilder.Entity("Models.ApplicantEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer")
                        .HasColumnName("applicant_id");

                    b.PrimitiveCollection<List<string>>("Attachments")
                        .HasColumnType("character varying(500)[]")
                        .HasColumnName("attachments");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Faculty")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("faculty");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("institution_name");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialization");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("applicant_educations_pkey");

                    b.HasIndex(new[] { "ApplicantId" }, "idx_applicant_educations_applicant_id");

                    b.ToTable("applicant_educations", (string)null);
                });

            modelBuilder.Entity("Models.ApplicantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Links")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("links")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PrivacySettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("privacy_settings")
                        .HasDefaultValueSql("'{\"hide_resume\": false, \"hide_responses\": false}'::jsonb");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .HasColumnType("character varying(100)[]")
                        .HasColumnName("skills");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thirdname")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("applicant_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "applicant_profiles_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_applicant_profiles_user_id");

                    b.ToTable("applicant_profiles", (string)null);
                });

            modelBuilder.Entity("Models.Contact", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ContactProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("contact_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "ContactProfileId")
                        .HasName("contacts_pkey");

                    b.HasIndex(new[] { "ContactProfileId" }, "idx_contacts_contact_id");

                    b.HasIndex(new[] { "UserId" }, "idx_contacts_user_id");

                    b.ToTable("contacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contacts_UserNotEqualContact", "user_id <> contact_id");
                        });
                });

            modelBuilder.Entity("Models.CuratorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.Property<string>("Thirdname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("thirdname");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("curator_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "curator_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("curator_profiles", (string)null);
                });

            modelBuilder.Entity("Models.EmployerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Inn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inn");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("legal_address");

                    b.Property<string>("MediaContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("media_content")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Socials")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("socials")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationData")
                        .HasColumnType("text")
                        .HasColumnName("verification_data");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_method");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("На рассмотрении")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("employer_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "employer_profiles_user_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_employer_profiles_user_id");

                    b.ToTable("employer_profiles", (string)null);
                });

            modelBuilder.Entity("Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("contacts")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateOnly?>("DeletedAt")
                        .HasColumnType("date")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnName("employer_id");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<DateOnly?>("ExpireAt")
                        .HasColumnType("date")
                        .HasColumnName("expire_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_address");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location_city");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MediaContentJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("media_content")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("OpportunityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opportunity_type");

                    b.Property<DateOnly>("PublishAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("publish_at")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("opportunities_pkey");

                    b.HasIndex(new[] { "EmployerId" }, "idx_opportunities_employer_id");

                    b.HasIndex(new[] { "LocationCity" }, "idx_opportunities_location_city");

                    b.HasIndex(new[] { "PublishAt" }, "idx_opportunities_publish_at");

                    b.HasIndex(new[] { "SearchVector" }, "idx_opportunities_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SearchVector" }, "idx_opportunities_search_vector"), "gin");

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("Models.OpportunityApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer")
                        .HasColumnName("applicant_id");

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.HasKey("Id")
                        .HasName("applications_pkey");

                    b.HasIndex(new[] { "OpportunityId", "ApplicantId" }, "applications_opportunity_id_applicant_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ApplicantId" }, "idx_applications_applicant_id");

                    b.HasIndex(new[] { "OpportunityId" }, "idx_applications_opportunity_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ProjectDetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("project_details_json");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("project_pkey");

                    b.HasIndex(new[] { "AuthorId" }, "idx_projects_author_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("RecommenderId")
                        .HasColumnType("integer")
                        .HasColumnName("recommender_id");

                    b.HasKey("Id")
                        .HasName("recommendations_pkey");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RecommenderId");

                    b.HasIndex(new[] { "OpportunityId" }, "idx_recommendations_opportunity_id");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Name" }, "tags_name_key")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_users_deleted_at")
                        .HasFilter("(deleted_at IS NOT NULL)");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Models.VApplicantStat", b =>
                {
                    b.Property<long?>("ApplicationCount")
                        .HasColumnType("bigint")
                        .HasColumnName("applications_count");

                    b.Property<long?>("ContactCount")
                        .HasColumnType("bigint")
                        .HasColumnName("contact_count");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<long?>("ProjectsCount")
                        .HasColumnType("bigint")
                        .HasColumnName("projects_count");

                    b.ToTable((string)null);

                    b.ToView("v_applicant_stats", (string)null);
                });

            modelBuilder.Entity("Models.VEmployerStat", b =>
                {
                    b.Property<long?>("CurrentOpportunitiesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("current_opportunities_count");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.ToTable((string)null);

                    b.ToView("v_employer_stats", (string)null);
                });

            modelBuilder.Entity("OpportunityTag", b =>
                {
                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("OpportunityId", "TagId")
                        .HasName("opportunity_tags_pkey");

                    b.HasIndex(new[] { "OpportunityId" }, "idx_opportunity_tags_opportunity_id");

                    b.HasIndex(new[] { "TagId" }, "idx_opportunity_tags_tag_id");

                    b.ToTable("opportunity_tags", (string)null);
                });

            modelBuilder.Entity("Models.ApplicantAchievement", b =>
                {
                    b.HasOne("Models.ApplicantProfile", "Applicant")
                        .WithMany("ApplicantAchievements")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applicant_achievements_applicant_id_fkey");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Models.ApplicantEducation", b =>
                {
                    b.HasOne("Models.ApplicantProfile", "Applicant")
                        .WithMany("ApplicantEducations")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applicant_educations_applicant_id_fkey");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Models.ApplicantProfile", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithOne("ApplicantProfile")
                        .HasForeignKey("Models.ApplicantProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applicant_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Contact", b =>
                {
                    b.HasOne("Models.User", "ContactProfile")
                        .WithMany()
                        .HasForeignKey("ContactProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contacts_user_id_fkey");

                    b.Navigation("ContactProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.CuratorProfile", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithOne("CuratorProfile")
                        .HasForeignKey("Models.CuratorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.EmployerProfile", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("Models.EmployerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Opportunity", b =>
                {
                    b.HasOne("Models.EmployerProfile", "Employer")
                        .WithMany("Opportunities")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("opportunities_employer_id_fkey");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Models.OpportunityApplication", b =>
                {
                    b.HasOne("Models.ApplicantProfile", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_applicant_id_fkey");

                    b.HasOne("Models.Opportunity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("applications_opportunity_id_fkey");

                    b.Navigation("Applicant");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.ApplicantProfile", "Author")
                        .WithMany("Projects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Models.Recommendation", b =>
                {
                    b.HasOne("Models.ApplicantProfile", "Candidate")
                        .WithMany("RecommendationCandidates")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recommendations_candidate_id_fkey");

                    b.HasOne("Models.Opportunity", "Opportunity")
                        .WithMany("Recommendations")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recommendations_opportunity_id_fkey");

                    b.HasOne("Models.ApplicantProfile", "Recommender")
                        .WithMany("RecommendationRecommenders")
                        .HasForeignKey("RecommenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recommendations_recommender_id_fkey");

                    b.Navigation("Candidate");

                    b.Navigation("Opportunity");

                    b.Navigation("Recommender");
                });

            modelBuilder.Entity("Models.Tag", b =>
                {
                    b.HasOne("Models.User", "CreatedByNavigation")
                        .WithMany("Tags")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("tags_created_by_fkey");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("OpportunityTag", b =>
                {
                    b.HasOne("Models.Opportunity", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("opportunity_tags_opportunity_id_fkey");

                    b.HasOne("Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("opportunity_tags_tag_id_fkey");
                });

            modelBuilder.Entity("Models.ApplicantProfile", b =>
                {
                    b.Navigation("ApplicantAchievements");

                    b.Navigation("ApplicantEducations");

                    b.Navigation("Applications");

                    b.Navigation("Projects");

                    b.Navigation("RecommendationCandidates");

                    b.Navigation("RecommendationRecommenders");
                });

            modelBuilder.Entity("Models.EmployerProfile", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Models.Opportunity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("ApplicantProfile");

                    b.Navigation("Contacts");

                    b.Navigation("CuratorProfile");

                    b.Navigation("EmployerProfile");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
